server:
  port: ${SERVER_PORT}
  forward-headers-strategy: ${SERVER_HEADERS_STRATEGY}

spring:
  hateoas:
    use-hal-as-default-json-media-type: ${SPRING_HATEOAS_HAL_MEDIA_TYPE_ENABLED}
  datasource:
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        transaction:
          coordinator_class: ${SPRING_SPA_PROPERTIES_HIBERNATED_CLASS}
    sql:
      init:
        mode: ${JPA_SQL_INIT_MODE}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    baseline-version: ${SPRING_FLYWAY_BASELINE_VERSION}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
  cache:
    type: ${SPRING_CACHE_TYPE}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING}
    enabled: ${MANAGEMENT_TRACING_ENABLED}
    propagation:
      type: ${MANAGEMENT_TRACING_PROPAGATION}
    otel:
      exporter:
        otlp:
          endpoint: ${MANAGEMENT_TRACING_OTEL_EXPORT_ENDPOINT}
          compression: ${MANAGEMENT_TRACING_OTEL_EXPORT_COMPRESSION}
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE}
  health:
    show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS}
    probes:
      enabled: ${MANAGEMENT_HEALTH_PROBES_ENABLED}
  info:
    env:
      enabled: ${MANAGEMENT_INFO_ENV_ENABLED}
  metrics:
    enable:
      all: ${MANAGEMENT_METRICS_ENABLE_ALL}
    export:
      prometheus:
        enabled: ${MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLE}
      otlp:
        enabled: ${MANAGEMENT_METRICS_OTPL_ENABLED}
  otlp:
    metrics:
      export:
        protocol: ${MANAGEMENT_OTPL_METRICS_EXPORT_PROTOCOL}
        url: ${MANAGEMENT_OTPL_METRICS_EXPORT_URL}
otel:
  logs:
    exporter: ${OTEL_LOGS_EXPORTER}
  metrics:
    exporter: ${OTEL_METRICS_EXPORTER}
  traces:
    exporter: ${OTEL_TRACES_EXPORTER}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL}