server:
  port: ${BACKEND_SERVER_PORT}
  forward-headers-strategy: framework

spring:

  zipkin:
    base-url: ${ZIPKIN_BASE_URL} #http://zipkin-service:9411
    sender:
      type: ${SPRING_ZIPKIN_SENDER_TYPE}
    #enabled: ${SPRING_ZIPKIN_ENABLED}

  hateoas:
    use-hal-as-default-json-media-type: false

  datasource:
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        transaction:
          coordinator_class: jdbc
    sql:
      init:
        mode: never

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    baseline-version: ${SPRING_FLYWAY_BASELINE_VERSION}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}

  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    show-details: always
    probes:
      enabled: true
  #info:
    #env:
      #enabled: true
  tracing:
    sampling:
      probability: 1.0
    #propagation:
      #type: b3
    #enabled: ${MANAGEMENT_TRACING_ENABLED}
    #zipkin:
      #tracing:
        #endpoint: ${MANAGEMENT_TRACING_ZIPKIN_TRACING_ENDPOINT}
      #connect-timeout: 5s
      #read-timeout: 5s